---
- hosts: all
  vars:
    trust_ca_configs:
      - name: test-target-01
        pki_dir: '{{ playbook_dir}}/test-pki'
      - name: test-target-02
        pki_dir: '{{ playbook_dir}}/test-pki'
  roles:
    - role: '{{ playbook_dir}}'
